### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by PolarisFTL** [mitming/AlignDet#27]
What is the cuda version, I'm having problems with the training process：

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by liming-ai** [comment]
> What is the cuda version, I'm having problems with the training process：
> 
> RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Thank you for your question. As long as the versions of your PyTorch and MM series installation packages match, this error should have nothing to do with my code. It may be that there is an incompatibility when you install mmdet or mmcv. I suggest you use conda to recreate the environment and try again.

**Comment by PolarisFTL** [comment]
Thanks for your reply, I fixed it yesterday, it was indeed a version mismatch issue.

**Comment by liming-ai** [comment]
> Thanks for your reply, I fixed it yesterday, it was indeed a version mismatch issue.

Glad to know that, best wishes to you
